/** \file
 *  This C header file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : ColorSetDef.g
 *     -                            On : 2011-02-27 23:08:07
 *     -                for the parser : ColorSetDefParserParser *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser ColorSetDefParser has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pColorSetDefParser, which is returned from a call to ColorSetDefParserNew().
 *
 * The methods in pColorSetDefParser are  as follows:
 *
 *  - graphics::color::colorsetdef::ColorSetDO*      pColorSetDefParser->colorSetDef(pColorSetDefParser)
 *  - void      pColorSetDefParser->colorDef(pColorSetDefParser)
 *  - void      pColorSetDefParser->solidColor(pColorSetDefParser)
 *  - void      pColorSetDefParser->linearColor(pColorSetDefParser)
 *  - void      pColorSetDefParser->linearColorDirection(pColorSetDefParser)
 *  - void      pColorSetDefParser->linerColorElement(pColorSetDefParser)
 *  - void      pColorSetDefParser->radialColor(pColorSetDefParser)
 *  - void      pColorSetDefParser->radialColorElement(pColorSetDefParser)
 *  - void      pColorSetDefParser->rgba(pColorSetDefParser)
 *  - void      pColorSetDefParser->hsba(pColorSetDefParser)
 *  - void      pColorSetDefParser->pos(pColorSetDefParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef _ColorSetDefParser_H
#define _ColorSetDefParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

// @parser::includes

#include "graphics/color/colorsetdef/ColorSetDef.h"
using namespace graphics::color;

inline float pu8tof(pANTLR3_UINT8 chars)
{
    return (float)_wtof((const wchar_t *)chars);
}

inline std::wstring trimSingleQuote(const std::wstring &s)
{
    size_t start = 0;
    size_t len = s.size();
    if (s.front() == L'\'') {
        start = 1;
        len--;
    }
    if (s.back() ==  L'\'') {
        len--;
    }
    return s.substr(start, len);
}

inline float getValue1(long value)
{
    return ((value & 0xff0000) >> 16) / 255.0f;
}

inline float getValue2(long value)
{
    return ((value & 0xff00) >> 8) / 255.0f;
}

inline float getValue3(long value)
{
    return (value & 0xff) / 255.0f;
}

inline void parse3values(pANTLR3_UINT8 _chars, float *value1, float *value2, float *value3)
{
    wchar_t *chars = (wchar_t*)_chars;
    wchar_t *offset;

    size_t len = wcslen(chars);
    if (len > 2) {
        if (chars[0] == L'0' && chars[1] == L'x') {
            long ret = wcstol(chars, &offset, 0);
            *value1 = getValue1(ret);
            *value2 = getValue2(ret);
            *value3 = getValue3(ret);
            return;
        }
    }
    if (len > 1) {
        if (chars[0] == L'#') {
            long ret = wcstol(chars + 1, &offset, 16);
            *value1 = getValue1(ret);
            *value2 = getValue2(ret);
            *value3 = getValue3(ret);
            return;
        }
    }
    long ret = wcstol(chars, &offset, 16);
    *value1 = getValue1(ret);
    *value2 = getValue2(ret);
    *value3 = getValue3(ret);
}



#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
    typedef struct ColorSetDefParser_Ctx_struct ColorSetDefParser, * pColorSetDefParser;



// @parser::header


#ifdef  ANTLR3_WINDOWS
// Disable: Unreferenced parameter,                         - Rules with parameters that are not used
//          constant conditional,                           - ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable                 - tree rewrite variables declared but not needed
//          Unreferenced local variable                     - lexer rule declares but does not always use _type
//          potentially unitialized variable used           - retval always returned from a rule
//          unreferenced local function has been removed    - susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

    /* globalAttributeScopeDecl(scope)
     */
    /* makeScopeSet()
     */
    /** Definition of the ColorSet scope variable tracking
    *  structure. An instance of this structure is created by calling
    *  ColorSetDefParser_ColorSetPush().
    */
    typedef struct  ColorSetDefParser_ColorSet_SCOPE_struct {
        /** Function that the user may provide to be called when the
         *  scope is destroyed (so you can free pANTLR3_HASH_TABLES and so on)
         *
         * \param POinter to an instance of this typedef/struct
         */
        void    (ANTLR3_CDECL *free)    (struct ColorSetDefParser_ColorSet_SCOPE_struct * frame);

        /* =============================================================================
         * Programmer defined variables...
         */
        graphics::color::colorsetdef::COLORVALUE_TYPE colorValueType;
        float value1;
        float value2;
        float value3;
        float value4;
        float position;
        graphics::color::colorsetdef::ColorSetDO* pColorSet;

        /* End of programmer defined variables
         * =============================================================================
         */
    }
    ColorSetDefParser_ColorSet_SCOPE, * pColorSetDefParser_ColorSet_SCOPE;

    /** Context tracking structure for ColorSetDefParser
     */
    struct ColorSetDefParser_Ctx_struct {
        /** Built in ANTLR3 context tracker contains all the generic elements
         *  required for context tracking.
         */
        pANTLR3_PARSER   pParser;
        /* globalAttributeScopeDef(scope)
         */
        /** Pointer to the  ColorSet stack for use by pColorSetDefParser_ColorSetPush()
         *  and pColorSetDefParser_ColorSetPop()
         */
        pANTLR3_STACK pColorSetDefParser_ColorSetStack;
        ANTLR3_UINT32 pColorSetDefParser_ColorSetStack_limit;
        /** Pointer to the top of the stack for the global scope pColorSetDefParser_ColorSetStack
         */
        pColorSetDefParser_ColorSet_SCOPE    (*pColorSetDefParser_ColorSetPush)(struct ColorSetDefParser_Ctx_struct * ctx);
        pColorSetDefParser_ColorSet_SCOPE    pColorSetDefParser_ColorSetTop;


        graphics::color::colorsetdef::ColorSetDO* (*colorSetDef)   (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*colorDef)   (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*solidColor) (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*linearColor)    (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*linearColorDirection)   (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*linerColorElement)  (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*radialColor)    (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*radialColorElement) (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*rgba)   (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*hsba)   (struct ColorSetDefParser_Ctx_struct * ctx);
        void (*pos)    (struct ColorSetDefParser_Ctx_struct * ctx);
        // Delegated rules

        const char * (*getGrammarFileName)();
        void            (*reset)  (struct ColorSetDefParser_Ctx_struct * ctx);
        void        (*free)   (struct ColorSetDefParser_Ctx_struct * ctx);

    };

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
    ANTLR3_API pColorSetDefParser ColorSetDefParserNew         (pANTLR3_COMMON_TOKEN_STREAM instream);
    ANTLR3_API pColorSetDefParser ColorSetDefParserNewSSD      (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

    /** Symbolic definitions of all the tokens that the parser will work with.
     * \{
     *
     * Antlr will define EOF, but we can't use that as it it is too common in
     * in C header files and that would be confusing. There is no way to filter this out at the moment
     * so we just undef it here for now. That isn't the value we get back from C recognizers
     * anyway. We are looking for ANTLR3_TOKEN_EOF.
     */
#ifdef  EOF
#undef  EOF
#endif
#ifdef  Tokens
#undef  Tokens
#endif
#define EOF      -1
#define T__16      16
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define ID      4
#define INT      5
#define HEX_DIGIT      6
#define HEXINT      7
#define EXPONENT      8
#define FLOAT      9
#define COMMENT      10
#define WS      11
#define ESC_SEQ      12
#define STRING      13
#define UNICODE_ESC      14
#define OCTAL_ESC      15
#ifdef  EOF
#undef  EOF
#define EOF ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

    /* End of token definitions for ColorSetDefParser
     * =============================================================================
     */
    /** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
