/** \file
 *  This C header file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : ColorSetDef.g
 *     -                            On : 2011-02-27 23:08:07
 *     -                 for the lexer : ColorSetDefLexerLexer *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer ColorSetDefLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pColorSetDefLexer, which is returned from a call to ColorSetDefLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pColorSetDefLexer are  as follows:
 *
 *  -  void      pColorSetDefLexer->T__16(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__17(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__18(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__19(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__20(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__21(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__22(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__23(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__24(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__25(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__26(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__27(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->T__28(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->ID(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->INT(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->HEXINT(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->FLOAT(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->COMMENT(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->WS(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->STRING(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->EXPONENT(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->HEX_DIGIT(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->ESC_SEQ(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->OCTAL_ESC(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->UNICODE_ESC(pColorSetDefLexer)
 *  -  void      pColorSetDefLexer->Tokens(pColorSetDefLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef _ColorSetDefLexer_H
#define _ColorSetDefLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

// @lexer::includes


#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
    typedef struct ColorSetDefLexer_Ctx_struct ColorSetDefLexer, * pColorSetDefLexer;



// @lexer::header
#define ANTLR3_INLINE_INPUT_UTF16

#include "graphics/color/colorsetdef/ColorSetDef.h"
    using namespace graphics::color;


#ifdef  ANTLR3_WINDOWS
// Disable: Unreferenced parameter,                         - Rules with parameters that are not used
//          constant conditional,                           - ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable                 - tree rewrite variables declared but not needed
//          Unreferenced local variable                     - lexer rule declares but does not always use _type
//          potentially unitialized variable used           - retval always returned from a rule
//          unreferenced local function has been removed    - susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

    /** Context tracking structure for ColorSetDefLexer
     */
    struct ColorSetDefLexer_Ctx_struct {
        /** Built in ANTLR3 context tracker contains all the generic elements
         *  required for context tracking.
         */
        pANTLR3_LEXER    pLexer;


        void (*mT__16) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__17) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__18) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__19) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__20) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__21) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__22) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__23) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__24) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__25) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__26) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__27) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mT__28) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mID)    (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mINT)   (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mHEXINT)    (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mFLOAT) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mCOMMENT)   (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mWS)    (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mSTRING)    (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mEXPONENT)  (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mHEX_DIGIT) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mESC_SEQ)   (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mOCTAL_ESC) (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mUNICODE_ESC)   (struct ColorSetDefLexer_Ctx_struct * ctx);
        void (*mTokens)    (struct ColorSetDefLexer_Ctx_struct * ctx);
        const char * (*getGrammarFileName)();
        void            (*reset)  (struct ColorSetDefLexer_Ctx_struct * ctx);
        void        (*free)   (struct ColorSetDefLexer_Ctx_struct * ctx);

    };

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
    ANTLR3_API pColorSetDefLexer ColorSetDefLexerNew         (pANTLR3_INPUT_STREAM instream);
    ANTLR3_API pColorSetDefLexer ColorSetDefLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

    /** Symbolic definitions of all the tokens that the lexer will work with.
     * \{
     *
     * Antlr will define EOF, but we can't use that as it it is too common in
     * in C header files and that would be confusing. There is no way to filter this out at the moment
     * so we just undef it here for now. That isn't the value we get back from C recognizers
     * anyway. We are looking for ANTLR3_TOKEN_EOF.
     */
#ifdef  EOF
#undef  EOF
#endif
#ifdef  Tokens
#undef  Tokens
#endif
#define EOF      -1
#define T__16      16
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define ID      4
#define INT      5
#define HEX_DIGIT      6
#define HEXINT      7
#define EXPONENT      8
#define FLOAT      9
#define COMMENT      10
#define WS      11
#define ESC_SEQ      12
#define STRING      13
#define UNICODE_ESC      14
#define OCTAL_ESC      15
#ifdef  EOF
#undef  EOF
#define EOF ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

    /* End of token definitions for ColorSetDefLexer
     * =============================================================================
     */
    /** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
